/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.victorhcamargo.padaria.Interface;

import edu.victorhcamargo.padaria.model.ProdutoVenda;
import edu.victorhcamargo.padaria.produtoservice.ProdutoService;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import edu.victorhcamargo.padaria.model.Produto;

/**
 *
 * @author Java_blessed
 */
public class Principal extends javax.swing.JFrame {
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());
    List<Produto> produtos;
    DefaultListModel<ProdutoVenda> listaCarrinho1;
    DefaultListModel<ProdutoVenda> listaCarrinho2;
    DefaultListModel<ProdutoVenda> listaCarrinho3;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        produtos = ProdutoService.inicializarProdutos();
        /*
        Produto p1 = new Produto();
        Produto p2 = new Produto();
        Produto p3 = new Produto();
    
        p3 = new Produto(3,20.90,"Pão Doce");
        p4 = new Produto(4,25.90,"Pão Australiano");
        p5 = new Produto(5,27.90,"Pão Semolina");
        p6 = new Produto(6,40.90,"Pão Caseiro");
        p1.setCodigo(1);
        p1.setPreco(25.90);awd
        p2.setCodigo(2);
        p2.setPreco(35.90);
        p2.setDescricao("Pão de queijo");
        p3.setCodigo(3);
        p3.setPreco(20.90);
        p3.setDescricao("Pão Doce");*/
        produtos.forEach(item ->{
            selecaoProduto.addItem(item);
        }
        );
        listaCarrinho1 = new DefaultListModel<>();
        jList1.setModel(listaCarrinho1);
        listaCarrinho2 = new DefaultListModel<>();
        jList2.setModel(listaCarrinho2);
        listaCarrinho3 = new DefaultListModel<>();
        jList3.setModel(listaCarrinho3);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void adicionarTotal(DefaultListModel<ProdutoVenda> listaCarrinho,JTextField campoTotal) {
        double total = 0;
                for(int i =0; i<listaCarrinho.getSize();i++){
                    total += listaCarrinho.getElementAt(i).getTotal();
                   
                } 
                campoTotal.setText("Total = "+ total);
    }
    public void saldo (ProdutoVenda produtoVendido, Character operador) {
        Produto prod = (Produto)selecaoProduto.getSelectedItem();
        switch (operador) {
            case '+':   
                        prod.setSaldoEstoque(prod.getSaldoEstoque()+produtoVendido.getQuantidade());
                        campoSaldo.setText(Integer.toString(
                                prod.getSaldoEstoque()
                        )
                        );
                        break;
            case '-':
                        prod.setSaldoEstoque(prod.getSaldoEstoque()-produtoVendido.getQuantidade());
                        campoSaldo.setText(Integer.toString(
                                prod.getSaldoEstoque()
                        )
                        );
                        break;
        }
        
    }
    public void inserirCampo(DefaultListModel<ProdutoVenda> listaCarrinho,JTextField campoTotal) {
        int quantidade = Integer.parseInt(
                quantidadeProduto
                .getValue()
                .toString()
        );
        Produto produto = (Produto)selecaoProduto
                .getSelectedItem();
        
        if(produto.getSaldoEstoque() >= quantidade){
                ProdutoVenda produtoVendido = new ProdutoVenda();
                produtoVendido.setProduto(
                        (Produto)selecaoProduto.getSelectedItem()
                );
                produtoVendido.setQuantidade(
                        quantidade
                );
                produtoVendido.setTotal();
                listaCarrinho.addElement(produtoVendido);
                adicionarTotal(listaCarrinho,campoTotal);
                saldo(produtoVendido,'-');
            }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoTexto1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoTexto2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        campoTexto3 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        selecaoProduto = new javax.swing.JComboBox<>();
        quantidadeProduto = new javax.swing.JSpinner();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        bRemove = new javax.swing.JButton();
        campoTotal1 = new javax.swing.JTextField();
        campoTotal2 = new javax.swing.JTextField();
        campoTotal3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        campoSaldo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Adiciona");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        campoTexto1.setColumns(20);
        campoTexto1.setRows(5);
        jScrollPane1.setViewportView(campoTexto1);

        jButton3.setText("Adiciona");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        campoTexto2.setColumns(20);
        campoTexto2.setRows(5);
        jScrollPane2.setViewportView(campoTexto2);

        campoTexto3.setColumns(20);
        campoTexto3.setRows(5);
        jScrollPane3.setViewportView(campoTexto3);

        jButton4.setText("Adiciona");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        selecaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecaoProdutoActionPerformed(evt);
            }
        });

        quantidadeProduto.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jScrollPane4.setViewportView(jList1);

        jList2.setToolTipText("");
        jScrollPane5.setViewportView(jList2);

        jScrollPane6.setViewportView(jList3);

        bRemove.setText("Remove");
        bRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoveActionPerformed(evt);
            }
        });

        campoTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTotal1ActionPerformed(evt);
            }
        });

        campoTotal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTotal2ActionPerformed(evt);
            }
        });

        campoTotal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTotal3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Saldo");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        campoSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(154, 154, 154)
                                            .addComponent(quantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(selecaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(campoTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(campoTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(913, 913, 913))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(bRemove))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 879, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(campoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(campoTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(bRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void fazerCompra(JTextArea areaDestino) {
        Produto produto = (Produto)selecaoProduto.getSelectedItem();
        if(produto.getSaldoEstoque() > 0 && produto.getSaldoEstoque() - Integer.parseInt(
                quantidadeProduto
                .getValue()
                .toString()
        ) >= 0) {
            double total = ((Produto)selecaoProduto.getSelectedItem()).getPreco() * Integer.parseInt(quantidadeProduto.getValue().toString());
            areaDestino.append(quantidadeProduto.getValue().toString());
            areaDestino.append("x ");
            areaDestino.append(selecaoProduto.getSelectedItem().toString());
            areaDestino.append(" = " + total);
            areaDestino.append("\n");
            if (areaDestino == campoTexto1){
                inserirCampo(listaCarrinho1,campoTotal1);
            } else if (areaDestino == campoTexto2){
                inserirCampo(listaCarrinho2,campoTotal2);
            } else if (areaDestino == campoTexto3){
                inserirCampo(listaCarrinho3,campoTotal3);
            }
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        fazerCompra(campoTexto1);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        fazerCompra(campoTexto2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        fazerCompra(campoTexto3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void bRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoveActionPerformed
        // TODO add your handling code here:
        
        if (jList1.getSelectedIndex() >=0)  {
            
            ProdutoVenda produtoRemovido = listaCarrinho1.remove(
                jList1.getSelectedIndex()
            );
            saldo(produtoRemovido,'+');
            adicionarTotal(listaCarrinho1,campoTotal1);
        }
        if (jList2.getSelectedIndex() >=0) {
            ProdutoVenda produtoRemovido = listaCarrinho1.remove(
                jList2.getSelectedIndex()
            );
            saldo(produtoRemovido,'+');
            adicionarTotal(listaCarrinho2,campoTotal2);
            
        }
        if(jList3.getSelectedIndex() >=0){
            ProdutoVenda produtoRemovido = listaCarrinho1.remove(
                jList3.getSelectedIndex()
            );
            saldo(produtoRemovido,'+');
            adicionarTotal(listaCarrinho3,campoTotal3);
        }
    }//GEN-LAST:event_bRemoveActionPerformed

    private void campoTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTotal1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoTotal1ActionPerformed

    private void campoTotal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTotal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTotal2ActionPerformed

    private void campoTotal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTotal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTotal3ActionPerformed

    private void campoSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSaldoActionPerformed

    private void selecaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecaoProdutoActionPerformed
        // TODO add your handling code here:
        campoSaldo.setText(Integer.toString((
                (Produto)selecaoProduto.getSelectedItem()).getSaldoEstoque())
        );
    }//GEN-LAST:event_selecaoProdutoActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRemove;
    private javax.swing.JTextField campoSaldo;
    private javax.swing.JTextArea campoTexto1;
    private javax.swing.JTextArea campoTexto2;
    private javax.swing.JTextArea campoTexto3;
    private javax.swing.JTextField campoTotal1;
    private javax.swing.JTextField campoTotal2;
    private javax.swing.JTextField campoTotal3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<ProdutoVenda> jList1;
    private javax.swing.JList<ProdutoVenda> jList2;
    private javax.swing.JList<ProdutoVenda> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner quantidadeProduto;
    private javax.swing.JComboBox<Produto> selecaoProduto;
    // End of variables declaration//GEN-END:variables
}
